# Python Numbers, Type Conversion and Mathematics

In this segment, you will learn about Python Number, Type Conversion, and Mathematics with the help of examples.

The number data types are used to store the numeric values.

Python supports integers, floating-point numbers and complex numbers. 
They are defined as int, float, and complex classes in Python.

int - holds signed integers of non-limited length.

float - holds floating decimal points and it's accurate up to 15 decimal places.

complex - holds complex numbers.

Python Numeric Data Type

Integers and floating points are separated by the presence or absence of a decimal point. 

For instance,

5 is an integer
5.42 is a floating-point number.

Complex numbers are written in the form, x + yj, where x is the real part and y is the imaginary part.

We can use the type() function to know which class a variable or a value belongs to.

In [1]:
num1 = 5
print(num1, 'is of type', type(num1))

num2 = 5.42
print(num2, 'is of type', type(num2))

num3 = 8+2j
print(num3, 'is of type', type(num3))

5 is of type <class 'int'>
5.42 is of type <class 'float'>
(8+2j) is of type <class 'complex'>


In the above example, we have created three variables named num1, num2 and num3 with values 5, 5.42, and 8+2j respectively.

We have also used the type() function to know which class a certain variable belongs to. Since,

5 is an integer value, type() returns int as the class of num1 i.e <class 'int'>
5.42 is a floating value, type() returns float as the class of num2 i.e <class 'float'>
1 + 2j is a complex number, type() returns complex as the class of num3 i.e <class 'complex'>

# Number Systems

The numbers we deal with every day are of the decimal (base 10) number system.

But computer programmers need to work with binary (base 2), hexadecimal (base 16) and octal (base 8) number systems.

In Python, we can represent these numbers by appropriately placing a prefix before that number. The following table lists these prefixes.

Number System	Prefix

Binary	0b or 0B

Octal	0o or 0O

Hexadecimal	0x or 0X

Here are some examples

In [4]:
print(0b1101011)  # prints 107

print(0xFB + 0b11)  # prints 253

print(0o15)  # prints 13

107
254
13


# Type Conversion in Python

In programming, type conversion is the process of converting one type of number into another.

Operations like addition, subtraction convert integers to float implicitly (automatically), 
if one of the operands is float. 

For example,

In [3]:
print(1 + 2.0) # prints 3.0

3.0


Here, we can see above that 1 (integer) is converted into 1.0 (float) for addition and 
the result is also a floating point number.


# Explicit Type Conversion

We can also use built-in functions like int(), float() and complex() to convert between types explicitly. 
These functions can even convert from strings.

In [4]:
num1 = int(2.3)
print(num1)  # prints 2

num2 = int(-2.8)
print(num2)  # prints -2

num3 = float(5)
print(num3) # prints 5.0

num4 = complex('3+5j')
print(num4)  # prints (3 + 5j)

2
-2
5.0
(3+5j)


Here, when converting from float to integer, the number gets truncated (decimal parts are removed).

Similarly when converting from integer to float, .0 is postfixed to the number.

# Python Random Module

Python offers the random module to generate random numbers or to pick a random item from an iterator.

First we need to import the random module. 

For example,

In [27]:
import random

print(random.randrange(10, 20))

list1 = ['a', 'b', 'c', 'd', 'e']

# get random item from list1
print(random.choice(list1))

# Shuffle list1
random.shuffle(list1)

# Print the shuffled list1
print(list1)

# Print random element
print(random.random())

19
a
['d', 'c', 'b', 'a', 'e']
0.5507846417600732


Execute above code multiple times to see the changes

You can generate random numbers in Python by using random module.

Python offers random module that can generate random numbers.

These are pseudo-random number as the sequence of number generated depends on the seed.

If the seeding value is same, the sequence will be the same. 

For example, if you use 2 as the seeding value, you will always see the following sequence.

In [29]:
import random
random.seed(3)

print(random.random())
print(random.random())
print(random.random())
print(random.random())

0.23796462709189137
0.5442292252959519
0.36995516654807925
0.6039200385961945


Now, execute above code many times, you will see no change in the sequence

seeding can be any integer number

# Python Mathematics

Python offers the math module to carry out different mathematics like 
trigonometry, logarithms, probability and statistics, etc. 

For example,

In [10]:
import math

print(math.pi)

print(math.cos(math.pi))

print(math.exp(10))

print(math.log10(1000))

print(math.sinh(1))

print(math.factorial(6))

3.141592653589793
-1.0
22026.465794806718
3.0
1.1752011936438014
720


One can check for more details about full list of functions and attributes available in the Python math module.

# Python List

Create a Python List

A list is created in Python by placing items inside [], separated by commas . For example,

In [11]:
# A list with 3 integers
numbers = [1, 2, 5]

print(numbers)

# Output: [1, 2, 5]

[1, 2, 5]


Here, we have created a list named numbers with 3 integer items.

A list can have any number of items and they may be of different types (integer, float, string, etc.). For example,

empty list

my_list = []

list with mixed data types

my_list = [1, "Hello", 3.4]

# Access Python List Elements

In Python, each item in a list is associated with a number. The number is known as a list index.

We can access elements of an array using the index number (0, 1, 2 …). For example,

In [13]:
languages = ["Python", "Swift", "C++"]

# access item at index 0
print(languages[0])   # Python

# access item at index 2
print(languages[2])   # C++

Python
C++


Here, we can see each list item is associated with the index number. And, we have used the index number to access the items.

Note: The list index always starts with 0. Hence, the first element of a list is present at index 0, not 1.

Negative Indexing in Python
Python allows negative indexing for its sequences. The index of -1 refers to the last item, -2 to 
the second last item and so on.

Let's see an example,

In [14]:
languages = ["Python", "Swift", "C++"]

# access item at index 0
print(languages[-1])   # C++

# access item at index 2
print(languages[-3])   # Python

C++
Python


# Slicing of a Python List

In Python it is possible to access a section of items from the list using the slicing operator :, 
not just a single item. For example,

In [15]:
# List slicing in Python

my_list = ['p','r','o','g','r','a','m','i','z']

# items from index 2 to index 4
print(my_list[2:5])

# items from index 5 to end
print(my_list[5:])

# items beginning to end
print(my_list[:])

['o', 'g', 'r']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


Here,

my_list[2:5] returns a list with items from index 2 to index 4.

my_list[5:] returns a list with items from index 1 to the end.

my_list[:] returns all list items

Note: When we slice lists, the start index is inclusive but the end index is exclusive.

# Add Elements to a Python List

Python List provides different methods to add items to a list.

1. Using append()

The append() method adds an item at the end of the list. For example,

In [16]:
numbers = [21, 34, 54, 12]

print("Before Append:", numbers)

# using append method
numbers.append(32)

print("After Append:", numbers)

Before Append: [21, 34, 54, 12]
After Append: [21, 34, 54, 12, 32]


In the above example, we have created a list named numbers. Notice the line,

numbers.append(32)

Here, append() adds 32 at the end of the array.

2. Using extend()

We use the extend() method to add all items of one list to another. For example,

In [17]:
prime_numbers = [2, 3, 5]
print("List1:", prime_numbers)

even_numbers = [4, 6, 8]
print("List2:", even_numbers)

# join two lists
prime_numbers.extend(even_numbers)

print("List after append:", prime_numbers) 

List1: [2, 3, 5]
List2: [4, 6, 8]
List after append: [2, 3, 5, 4, 6, 8]


In the above example, we have two lists named prime_numbers and even_numbers. Notice the statement,

prime_numbers.extend(even_numbers)

Here, we are adding all elements of even_numbers to prime_numbers.

# Change List Items
Python lists are mutable. Meaning lists are changeable. 
And, we can change items of a list by assigning new values using = operator. For example,

In [18]:
languages = ['Python', 'Swift', 'C++']

# changing the third item to 'C'
languages[2] = 'C'

print(languages)  # ['Python', 'Swift', 'C']

['Python', 'Swift', 'C']


Here, initially the value at index 3 is 'C++'. We then changed the value to 'C' using

languages[2] = 'C'

# Remove an Item From a List
1. Using del()

In Python we can use the del statement to remove one or more items from a list. For example,

In [19]:
languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']

# deleting the second item
del languages[1]
print(languages) # ['Python', 'C++', 'C', 'Java', 'Rust', 'R']

# deleting the last item
del languages[-1]
print(languages) # ['Python', 'C++', 'C', 'Java', 'Rust']

# delete first two items
del languages[0 : 2]  # ['C', 'Java', 'Rust']
print(languages)

['Python', 'C++', 'C', 'Java', 'Rust', 'R']
['Python', 'C++', 'C', 'Java', 'Rust']
['C', 'Java', 'Rust']


2. Using remove()

We can also use the remove() method to delete a list item. For example,

In [31]:
languages = ['Python', 'Swift', 'C++', 'C', 'Java', 'Rust', 'R']

# remove 'Python' from the list
languages.remove('Python')

print(languages) # ['Swift', 'C++', 'C', 'Java', 'Rust', 'R']
#dir(list)

['Swift', 'C++', 'C', 'Java', 'Rust', 'R']


# Python List Methods

Python has many useful list methods that makes it really easy to work with lists.

Method	Description

append()	add an item to the end of the list

extend()	add items of lists and other iterables to the end of the list

insert()	inserts an item at the specified index

remove()	removes item present at the given index

pop()	returns and removes item present at the given index

clear()	removes all items from the list

index()	returns the index of the first matched item

count()	returns the count of the specified item in the list

sort()	sort the list in ascending/descending order

reverse()	reverses the item of the list

copy()	returns the shallow copy of the list

# Iterating through a List

We can use the for loop to iterate over the elements of a list. For example,

In [19]:
languages = ['Python', 'Swift', 'C++', 'pranav']

# iterating through the list
for abc in languages:
    print(abc)

Python
Swift
C++
pranav


# Check if an Item Exists in the Python List

We use the in keyword to check if an item exists in the list or not. For example,

In [22]:
languages = ['Python', 'Swift', 'C++']

print('C' in languages)    # False
print('Python' in languages)    # True

False
True


Here,

'C' is not present in languages, 'C' in languages evaluates to False.

'Python' is present in languages, 'Python' in languages evaluates to True.

# Python List Length

In Python, we use the len() function to find the number of elements present in a list. For example,

In [23]:
languages = ['Python', 'Swift', 'C++']

print("List: ", languages)

print("Total Elements: ", len(languages))    # 3

List:  ['Python', 'Swift', 'C++']
Total Elements:  3


# Python List Comprehension

List comprehension is a concise and elegant way to create lists.

A list comprehension consists of an expression followed by the for statement inside square brackets.

Here is an example to make a list with each item being increasing by power of 2.

In [24]:
numbers = [number*number for number in range(1, 6)]

print(numbers)    

# Output: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In the above example, we have used the list comprehension to make a list with each item being increased by power of 2. 

Notice the code,

[number*x for x in range(1, 6)] 

The code above means to create a list of number*number where number takes values from 1 to 5

The code above,

numbers = [x*x for x in range(1, 6)]

is equivalent to

In [29]:
numbers1 = []

for x in range(1, 6):
    numbers1.append(x * x)

In [30]:
numbers1

[1, 4, 9, 16, 25]

# Python Tuple

A tuple in Python is similar to a list. The difference between the two is that we cannot change the elements of a tuple once it is assigned whereas we can change the elements of a list.

# Creating a Tuple

A tuple is created by placing all the items (elements) inside parentheses (), separated by commas. 
The parentheses are optional, however, it is a good practice to use them.

A tuple can have any number of items and they may be of different types (integer, float, list, string, etc.).

In [31]:
# Different types of tuples

# Empty tuple
my_tuple = ()
print(my_tuple)

# Tuple having integers
my_tuple = (1, 2, 3)
print(my_tuple)

# tuple with mixed datatypes
my_tuple = (1, "Hello", 3.4)
print(my_tuple)

# nested tuple
my_tuple = ("mouse", [8, 4, 6], (1, 2, 3))
print(my_tuple)

()
(1, 2, 3)
(1, 'Hello', 3.4)
('mouse', [8, 4, 6], (1, 2, 3))


In the above example, we have created different types of tuples and stored different data items inside them.

As mentioned earlier, we can also create tuples without using parentheses:

my_tuple = 1, 2, 3

my_tuple = 1, "Hello", 3.4

# Create a Python Tuple With one Element

In Python, creating a tuple with one element is a bit tricky. Having one element within parentheses is not enough.

We will need a trailing comma to indicate that it is a tuple,

In [32]:
var1 = ("Hello") # string
var2 = ("Hello",) # tuple

We can use the type() function to know which class a variable or a value belongs to.

In [33]:
var1 = ("hello")
print(type(var1))  # <class 'str'>

# Creating a tuple having one element
var2 = ("hello",)
print(type(var2))  # <class 'tuple'>

# Parentheses is optional
var3 = "hello",
print(type(var3))  # <class 'tuple'>

<class 'str'>
<class 'tuple'>
<class 'tuple'>


Here,

("hello") is a string so type() returns str as class of var1 i.e. <class 'str'>

("hello",) and "hello", both are tuples so type() returns tuple as class of var2 n var3 i.e. <class 'tuple'>

# Access Python Tuple Elements

Like a list, each element of a tuple is represented by index numbers (0, 1, ...) where the first element is at index 0.

We use the index number to access tuple elements. For example,

1. Indexing

We can use the index operator [] to access an item in a tuple, where the index starts from 0.

So, a tuple having 6 elements will have indices from 0 to 5. 
Trying to access an index outside of the tuple index range( 6,7,... in this example) will raise an IndexError.

The index must be an integer, so we cannot use float or other types. This will result in TypeError.

Likewise, nested tuples are accessed using nested indexing, as shown in the example below.

In [34]:
# accessing tuple elements using indexing
letters = ("p", "r", "o", "g", "r", "a", "m", "i", "z")

print(letters[0])   # prints "p" 
print(letters[5])   # prints "a"

p
a


In the above example,

letters[0] - accesses the first element
letters[5] - accesses the sixth element

# 2. Negative Indexing

Python allows negative indexing for its sequences.

The index of -1 refers to the last item, -2 to the second last item and so on. For example,

In [36]:
# accessing tuple elements using negative indexing
letters = ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

print(letters[-1])   # prints 'z' 
print(letters[-3])   # prints 'm'

z
m


In the above example,

letters[-1] - accesses last element
letters[-3] - accesses third last element

# 3. Slicing

We can access a range of items in a tuple by using the slicing operator colon :

In [37]:
# accessing tuple elements using slicing
my_tuple = ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

# elements 2nd to 4th index
print(my_tuple[1:4])  #  prints ('r', 'o', 'g')

# elements beginning to 2nd
print(my_tuple[:-7]) # prints ('p', 'r')

# elements 8th to end
print(my_tuple[7:]) # prints ('i', 'z')

# elements beginning to end
print(my_tuple[:]) # Prints ('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')

('r', 'o', 'g')
('p', 'r')
('i', 'z')
('p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z')


Here,

my_tuple[1:4] returns a tuple with elements from index 1 to index 3.

my_tuple[:-7] returns a tuple with elements from beginning to index 2.

my_tuple[7:] returns a tuple with elements from index 7 to the end.

my_tuple[:] returns all tuple items.

Note: When we slice lists, the start index is inclusive but the end index is exclusive.

# Python Tuple Methods

In Python ,methods that add items or remove items are not available with tuple. Only the following two methods are available.

Some examples of Python tuple methods:

In [38]:
my_tuple = ('a', 'p', 'p', 'l', 'e',)

print(my_tuple.count('p'))  # prints 2
print(my_tuple.index('l'))  # prints 3

2
3


Here,

my_tuple.count('p') - counts total number of 'p' in my_tuple

my_tuple.index('l') - returns the first occurrence of 'l' in my_tuple

# Iterating through a Tuple in Python

We can use the for loop to iterate over the elements of a tuple. For example,

In [39]:
languages = ('Python', 'Swift', 'C++')

# iterating through the tuple
for language in languages:
    print(language)

Python
Swift
C++


# Check if an Item Exists in the Python Tuple

We use the in keyword to check if an item exists in the tuple or not. For example,

In [40]:
languages = ('Python', 'Swift', 'C++')

print('C' in languages)    # False
print('Python' in languages)    # True

False
True


Here,

'C' is not present in languages, 'C' in languages evaluates to False.

'Python' is present in languages, 'Python' in languages evaluates to True.

# Advantages of Tuple over List in Python

Since tuples are quite similar to lists, both of them are used in similar situations.

However, there are certain advantages of implementing a tuple over a list:

We generally use tuples for heterogeneous (different) data types and lists for homogeneous (similar) data types.

Since tuples are immutable, iterating through a tuple is faster than with a list. So there is a slight performance boost.

Tuples that contain immutable elements can be used as a key for a dictionary. With lists, this is not possible.

If you have data that doesn't change, implementing it as tuple will guarantee that it remains write-protected.

# Python Strings

In computer programming, a string is a sequence of characters. For example, 
"hello" is a string containing a sequence of characters 'h', 'e', 'l', 'l', and 'o'.

We use single quotes or double quotes to represent a string in Python. For example,

In [42]:
# create a string using double quotes
string1 = "Python programming"

# create a string using single quotes
string1 = 'Python programming'

Here, we have created a string variable named string1. The variable is initialized with the string Python Programming.

# Example: Python String

In [43]:
# create string type variables

name = "Python"
print(name)

message = "I love Python."
print(message)

Python
I love Python.


In the above example, we have created string-type variables: name and 
message with values "Python" and "I love Python" respectively.

Here, we have used double quotes to represent strings but we can use single quotes too.

# Access String Characters in Python

We can access the characters in a string in three ways.

Indexing: One way is to treat strings as a list and use index values. For example,

In [44]:
greet = 'hello'

# access 1st index element
print(greet[1]) # "e"

e


# Negative Indexing: Similar to a list, Python allows negative indexing for its strings. 

For example,


In [45]:
greet = 'hello'

# access 4th last element
print(greet[-4]) # "e"

e


In [46]:
greet = 'hello'

# access 4th last element
print(greet[-4]) # "e"

e


Slicing: Access a range of characters in a string by using the slicing operator colon :. For example,

In [47]:
greet = 'Hello'

# access character from 1st index to 3rd index
print(greet[1:4])  # "ell"

ell


Note: If we try to access an index out of the range or use numbers other than an integer, we will get errors.

# Python Strings are immutable

In Python, strings are immutable. That means the characters of a string cannot be changed. For example,

In [48]:
message = 'Hola Amigos'
message[0] = 'H'
print(message)

TypeError: 'str' object does not support item assignment

TypeError: 'str' object does not support item assignment
    
However, we can assign the variable name to a new string. 

For example,

In [50]:
message = 'Hola Amigos'

# assign new string to message variable
message = 'Hello Friends'

print(message); # prints "Hello Friends"

Hello Friends


# 
Python Multiline String
We can also create a multiline string in Python. For this, 
we use triple double quotes """ or triple single quotes '''. For example,

In [51]:
# multiline string 
message = """
Never gonna give you up
Never gonna let you down
"""

print(message)


Never gonna give you up
Never gonna let you down



In the above example, anything inside the enclosing triple-quotes is one multiline string.



# Python String Operations
There are many operations that can be performed with strings which makes it one of the most used data types in Python.

1. Compare Two Strings

We use the == operator to compare two strings. If two strings are equal, 
the operator returns True. Otherwise, it returns False. For example,

In [52]:
str1 = "Hello, world!"
str2 = "I love Python."
str3 = "Hello, world!"

# compare str1 and str2
print(str1 == str2)

# compare str1 and str3
print(str1 == str3)

False
True


In the above example,

str1 and str2 are not equal. Hence, the result is False.

str1 and str3 are equal. Hence, the result is True.

2. Join Two or More Strings

In Python, we can join (concatenate) two or more strings using the + operator.

In [53]:
greet = "Hello, "
name = "Jack"

# using + operator
result = greet + name
print(result)

# Output: Hello, Jack

Hello, Jack


In the above example, we have used the + operator to join two strings: greet and name.

# Iterate Through a Python String

We can iterate through a string using a for loop. For example,

In [39]:
greet = 'world'

# iterating through greet string
for letter in greet:
    print(letter)

w
o
r
l
d


# Python String Length

In Python, we use the len() method to find the length of a string. For example,

In [55]:
greet = 'Hello'

# count length of greet string
print(len(greet))

# Output: 5

5


# String Membership Test

We can test if a substring exists within a string or not, using the keyword in.

In [57]:
print('a' in 'program') # True
print('at' not in 'battle') #False

True
False


# Methods of Python String

Besides those mentioned above, there are various string methods present in Python. Here are some of those methods:

Methods	Description

upper()	converts the string to uppercase

lower()	converts the string to lowercase

partition()	returns a tuple

replace()	replaces substring inside

find()	returns the index of first occurrence of substring

rstrip()	removes trailing characters

split()	splits string from left

startswith()	checks if string starts with the specified string

isnumeric()	checks numeric characters

index()	returns index of substring

# Escape Sequences in Python

The escape sequence is used to escape some of the characters present inside a string.

Suppose we need to include both double quote and single quote inside a string,

In [33]:
example = "He said, "What's there?""

print(example) # throws error

SyntaxError: invalid syntax (Temp/ipykernel_20584/2093257531.py, line 1)

Since strings are represented by single or double quotes, the compiler will treat "He said, " as the string. 
Hence, the above code will cause an error.

To solve this issue, we use the escape character \ in Python.

In [34]:
# escape double quotes
example = "He said, \"What's there?\""

print(example)

# escape single quotes
example = 'He said, "What\'s there?"'

print(example)

# Output: He said, "What's there?"

He said, "What's there?"
He said, "What's there?"


Here is a list of all the escape sequences supported by Python.

Escape Sequence	Description

\\	Backslash

\'	Single quote

\"	Double quote

\a	ASCII Bell

\b	ASCII Backspace

\f	ASCII Formfeed

\n	ASCII Linefeed

\r	ASCII Carriage Return

\t	ASCII Horizontal Tab

\v	ASCII Vertical Tab

\ooo	Character with octal value ooo

\xHH	Character with hexadecimal value HH

# Python String Formatting (f-Strings)

Python f-Strings make it really easy to print values and variables. For example,

In [38]:
name = 'Cathy'
country = 'UK'
age = 35

#print(name,country,age)

print(f'{name} is from {country} and his age is {age}')

Cathy is from UK and his age is 35


Here, f'{name} is from {country}' is an f-string.

This new formatting syntax is powerful and easy to use. From now on, we will use f-Strings to print strings and variables.

# Python Sets

A set is a collection of unique data. That is, elements of a set cannot be duplicate. For example,

Suppose we want to store information about student IDs. Since student IDs cannot be duplicate, we can use a set.

# Create a Set in Python
In Python, we create sets by placing all the elements inside curly braces {}, separated by comma.

A set can have any number of items and they may be of different types (integer, float, tuple, string etc.).
But a set cannot have mutable elements like lists, sets or dictionaries as its elements.

Let's see an example,

In [65]:
# create a set of integer type
student_id = {112, 114, 116, 118, 115}
print('Student ID:', student_id)

# create a set of string type
vowel_letters = {'a', 'e', 'i', 'o', 'u'}
print('Vowel Letters:', vowel_letters)

# create a set of mixed data types
mixed_set = {'Hello', 101, -2, 'Bye'}
print('Set of mixed data types:', mixed_set)

Student ID: {112, 114, 115, 116, 118}
Vowel Letters: {'e', 'a', 'i', 'u', 'o'}
Set of mixed data types: {'Bye', 101, 'Hello', -2}


In the above example, we have created different types of sets by placing all the elements inside the curly braces {}.

Note: When you run this code, you might get output in a different order. This is because the set has no particular order.

# Create an Empty Set in Python

Creating an empty set is a bit tricky. Empty curly braces {} will make an empty dictionary in Python.

To make a set without any elements, we use the set() function without any argument. For example,

In [66]:
# create an empty set
empty_set = set()

# create an empty dictionary
empty_dictionary = { }

# check data type of empty_set
print('Data type of empty_set:', type(empty_set))

# check data type of dictionary_set
print('Data type of empty_dictionary', type(empty_dictionary))

Data type of empty_set: <class 'set'>
Data type of empty_dictionary <class 'dict'>


Here,

empty_set - an empty set created using set()
empty_dictionary - an empty dictionary created using {}
Finally we have used the type() function to know which class empty_set and empty_dictionary belong to.

# Duplicate Items in a Set

Let's see what will happen if we try to include duplicate items in a set.

In [42]:
numbers = {22, 44, 6, 6, 22, 8,9,10,11,9}
print(numbers)   # {8, 2, 4, 6}

{6, 22, 8, 9, 10, 11, 44}


Here, we can see there are no duplicate items in the set as a set cannot contain duplicates.

# Add and Update Set Items in Python

Sets are mutable. However, since they are unordered, indexing has no meaning.

We cannot access or change an element of a set using indexing or slicing. Set data type does not support it.

# Add Items to a Set in Python

In Python, we use the add() method to add an item to a set. For example,

In [69]:
numbers = {21, 34, 54, 12}

print('Initial Set:',numbers)

# using add() method
numbers.add(32)

print('Updated Set:', numbers) 

Initial Set: {34, 12, 21, 54}
Updated Set: {32, 34, 12, 21, 54}


# Update Python Set

The update() method is used to update the set with items other collection types (lists, tuples, sets, etc). For example,

In [70]:
companies = {'Lacoste', 'Ralph Lauren'}
tech_companies = ['apple', 'google', 'apple']

companies.update(tech_companies)

print(companies)

# Output: {'google', 'apple', 'Lacoste', 'Ralph Lauren'}

{'google', 'Ralph Lauren', 'Lacoste', 'apple'}


Here, all the unique elements of tech_companies are added to the companies set.

# Remove an Element from a Set

We use the discard() method to remove the specified element from a set. For example,

In [71]:
languages = {'Swift', 'Java', 'Python'}

print('Initial Set:',languages)

# remove 'Java' from a set
removedValue = languages.discard('Java')

print('Set after remove():', languages)

Initial Set: {'Python', 'Swift', 'Java'}
Set after remove(): {'Python', 'Swift'}


Here, we have used the discard() method to remove 'Java' from the languages set.

# Built-in Functions with Set

Built-in functions like all(), any(), enumerate(), len(), max(), min(), sorted(), sum() etc. 
are commonly used with sets to perform different tasks.

Function	Description

all()	Returns True if all elements of the set are true (or if the set is empty).

any()	Returns True if any element of the set is true. If the set is empty, returns False.

enumerate()	Returns an enumerate object. It contains the index and value for all the items of the set as a pair.

len()	Returns the length (the number of items) in the set.

max()	Returns the largest item in the set.

min()	Returns the smallest item in the set.

sorted()	Returns a new sorted list from elements in the set(does not sort the set itself).

sum()	Returns the sum of all elements in the set.

# Iterate Over a Set in Python

In [74]:
fruits = {"Apple", "Peach", "Mango"}

# for loop to access each fruits
for fruit in fruits: 
    print(fruit)

Peach
Mango
Apple


# Find Number of Set Elements

We can use the len() method to find the number of elements present in a Set. For example,

In [75]:
even_numbers = {2,4,6,8}
print('Set:',even_numbers)

# find number of elements
print('Total Elements:', len(even_numbers))

Set: {8, 2, 4, 6}
Total Elements: 4


Here, we have used the len() method to find the number of elements present in a Set.

# Python Set Operations

Python Set provides different built-in methods to perform mathematical set operations like union, 
intersection, subtraction, and symmetric difference.

Union of Two Sets
The union of two sets A and B include all the elements of set A and B.

We use the | operator or the union() method to perform the set union operation. For example,

In [76]:
# first set
A = {1, 3, 5}

# second set
B = {0, 2, 4}

# perform union operation using |
print('Union using |:', A | B)

# perform union operation using union()
print('Union using union():', A.union(B)) 

Union using |: {0, 1, 2, 3, 4, 5}
Union using union(): {0, 1, 2, 3, 4, 5}


Note: A|B and union() is equivalent to A ⋃ B set operation.

# Set Intersection

The intersection of two sets A and B include the common elements between set A and B.

In Python, we use the & operator or the intersection() method to perform the set intersection operation. For example,

In [77]:
# first set
A = {1, 3, 5}

# second set
B = {1, 2, 3}

# perform intersection operation using &
print('Intersection using &:', A & B)

# perform intersection operation using intersection()
print('Intersection using intersection():', A.intersection(B)) 

Intersection using &: {1, 3}
Intersection using intersection(): {1, 3}


Note: A&B and intersection() is equivalent to A ⋂ B set operation.

# Difference between Two Sets

The difference between two sets A and B include elements of set A that are not present on set B.

We use the - operator or the difference() method to perform the difference between two sets. For example,

In [80]:
# first set
A = {2, 3, 5}

# second set
B = {1, 2, 6}

# perform difference operation using -
print('Difference using -:', A - B)

# perform difference operation using difference()
print('Difference using difference():', A.difference(B)) 

Difference using -: {3, 5}
Difference using difference(): {3, 5}


Note: A - B and A.difference(B) is equivalent to A - B set operation.

# Set Symmetric Difference

The symmetric difference between two sets A and B includes all elements of A and B without the common elements.

In Python, we use the ^ operator or the symmetric_difference() method to perform symmetric difference between two sets. 

For example,

In [81]:
# first set
A = {2, 3, 5}

# second set
B = {1, 2, 6}

# perform difference operation using ^
print('using ^:', A ^ B)

# using symmetric_difference()
print('using symmetric_difference():', A.symmetric_difference(B)) 

using ^: {1, 3, 5, 6}
using symmetric_difference(): {1, 3, 5, 6}


# Check if two sets are equal

We can use the == operator to check whether two sets are equal or not. For example,

In [83]:
# first set
A = {1, 3, 5}

# second set
B = {3, 5, 1}

# perform difference operation using ==
if A == B:
    print('Set A and Set B are equal')
else:
    print('Set A and Set B are not equal')

Set A and Set B are equal


In the above example, A and B have the same elements, so the condition

if A == B

evaluates to True. Hence, the statement print('Set A and Set B are equal') inside the if is executed.

# Other Python Set Methods

There are many set methods, some of which we have already used above. 
Here is a list of all the methods that are available with the set objects:

Method	Description

add()	Adds an element to the set

clear()	Removes all elements from the set

copy()	Returns a copy of the set

difference()	Returns the difference of two or more sets as a new set

difference_update()	Removes all elements of another set from this set

discard()	Removes an element from the set if it is a member. (Do nothing if the element is not in set)

intersection()	Returns the intersection of two sets as a new set

intersection_update()	Updates the set with the intersection of itself and another

isdisjoint()	Returns True if two sets have a null intersection

issubset()	Returns True if another set contains this set

issuperset()	Returns True if this set contains another set

pop()	Removes and returns an arbitrary set element. Raises KeyError if the set is empty

remove()	Removes an element from the set. If the element is not a member, raises a KeyError

symmetric_difference()	Returns the symmetric difference of two sets as a new set

symmetric_difference_update()	Updates a set with the symmetric difference of itself and another

union()	Returns the union of sets in a new set

update()	Updates the set with the union of itself and others

# Python Dictionary

Python dictionary is an ordered collection (starting from Python 3.7) of items. 
It stores elements in key/value pairs. Here, keys are unique identifiers that are associated with each value.

Let's see an example,

If we want to store information about countries and their capitals, 
we can create a dictionary with country names as keys and capitals as values.

Keys	Values

Nepal	Kathmandu

Italy	Rome

England	London


# Create a dictionary in Python

Here's how we can create a dictionary in Python.

In [84]:
capital_city = {"Nepal": "Kathmandu", "Italy": "Rome", "England": "London"}
print(capital_city)

{'Nepal': 'Kathmandu', 'Italy': 'Rome', 'England': 'London'}


In the above example, we have created a dictionary named capital_city. Here,

Keys are "Nepal", "Italy", "England"

Values are "Kathmandu", "Rome", "London"

Note: Here, keys and values both are of string type. We can also have keys and values of different data types.

# Example 1: Python Dictionary

In [85]:
# dictionary with keys and values of different data types
numbers = {1: "One", 2: "Two", 3: "Three"}
print(numbers)

{1: 'One', 2: 'Two', 3: 'Three'}


In the above example, we have created a dictionary named numbers. Here, keys are of integer type and values are of string type.

# Add Elements to a Python Dictionary

We can add elements to a dictionary using the name of the dictionary with []. For example,

In [86]:
capital_city = {"Nepal": "Kathmandu", "England": "London"}
print("Initial Dictionary: ",capital_city)

capital_city["Japan"] = "Tokyo"

print("Updated Dictionary: ",capital_city)

Initial Dictionary:  {'Nepal': 'Kathmandu', 'England': 'London'}
Updated Dictionary:  {'Nepal': 'Kathmandu', 'England': 'London', 'Japan': 'Tokyo'}


In the above example, we have created a dictionary named capital_city. Notice the line,

capital_city["Japan"] = "Tokyo"

Here, we have added a new element to capital_city with key: Japan and value: Tokyo.

# Change Value of Dictionary

In [87]:
student_id = {111: "Eric", 112: "Kyle", 113: "Butters"}
print("Initial Dictionary: ", student_id)

student_id[112] = "Stan"

print("Updated Dictionary: ", student_id)

Initial Dictionary:  {111: 'Eric', 112: 'Kyle', 113: 'Butters'}
Updated Dictionary:  {111: 'Eric', 112: 'Stan', 113: 'Butters'}


In the above example, we have created a dictionary named student_id. Initially, the value associated with the key 112 is "Kyle". 
Now, notice the line,

student_id[112] = "Stan"

Here, we have changed the value associated with the key 112 to "Stan".

# Accessing Elements from Dictionary

In Python, we use the keys to access their corresponding values. For example,

In [88]:
student_id = {111: "Eric", 112: "Kyle", 113: "Butters"}

print(student_id[111])  # prints Eric
print(student_id[113])  # prints Butters

Eric
Butters


Here, we have used the keys to access their corresponding values.

If we try to access the value of a key that doesn't exist, we'll get an error. For example,

In [89]:
student_id = {111: "Eric", 112: "Kyle", 113: "Butters"}
print(student_id[211])  

# Output: KeyError: 211

KeyError: 211

# Removing elements from Dictionary

We use the del statement to remove an element from the dictionary. For example,

In [90]:
student_id = {111: "Eric", 112: "Kyle", 113: "Butters"}

print("Initial Dictionary: ", student_id)

del student_id[111]

print("Updated Dictionary ", student_id)

Initial Dictionary:  {111: 'Eric', 112: 'Kyle', 113: 'Butters'}
Updated Dictionary  {112: 'Kyle', 113: 'Butters'}


Here, we have created a dictionary named student_id. Notice the code,

del student_id[111]

The del statement removes the element associated with the key 111.

We can also delete the whole dictionary using the del statement,

In [91]:
student_id = {111: "Eric", 112: "Kyle", 113: "Butters"}

# delete student_id dictionary
del student_id

print(student_id)

# Output: NameError: name 'student_id' is not defined

NameError: name 'student_id' is not defined

We are getting an error message because we have deleted the student_id dictionary and student_id doesn't exist anymore.

# Python Dictionary Methods

Methods that are available with a dictionary are tabulated below. Some of them have already been used in the above examples.

Function	Description

all()	Return True if all keys of the dictionary are True (or if the dictionary is empty).

any()	Return True if any key of the dictionary is true. If the dictionary is empty, return False.

len()	Return the length (the number of items) in the dictionary.

sorted()	Return a new sorted list of keys in the dictionary.

clear()	Removes all items from the dictionary.

keys()	Returns a new object of the dictionary's keys.

values()	Returns a new object of the dictionary's values

# Dictionary Membership Test
We can test if a key is in a dictionary or not using the keyword in. 
Notice that the membership test is only for the keys and not for the values.

In [93]:
# Membership Test for Dictionary Keys
squares = {1: 1, 3: 9, 5: 25, 7: 49, 9: 81}

# Output: True
print(1 in squares) # prints True

print(2 not in squares) # prints True

# membership tests for key only not value
print(49 in squares) # prints false

True
True
False


# Iterating Through a Dictionary

We can iterate through each key in a dictionary using a for loop.

In [46]:
# Iterating through a Dictionary
squares = {1: 1, 3: 9, 5: 25, 7: 49, 9: 81}
for i in squares:
    print(squares[i])

1
9
25
49
81


In [48]:
#This type of problem
num = 10

while num > 5:
    print(num,end= ' ')
    
    num = num - 1
    if num == 8:
        num = 2

10 9 

In [49]:
for letter in 'cloudyml':
    if (letter == 'c') or (letter == 'o'):
        print('m', end= ' ')
    else:
        print(letter,end= 'x')

m lxm uxdxyxmxlx